# Generated by Django 3.0.7 on 2020-07-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prpduct',
            new_name='Product',
        ),
    ]
